server:
  port: 80
spring:
  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/feng-cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: mysql
    openInView: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          format_sql: true
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
